{-|
  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:

  By considering the terms in the Fibonacci sequence whose values do not exceed
  N, find the sum of the even-valued terms.

  Input Format
  First line contains that denotes the number of test cases. This is followed
  by lines, each containing an integer, .

  Output Format
  Print the required answer for each test case.

  Sample Input

  2
  10
  100

  Sample Output

  10
  44
-}

import Control.Monad (replicateM_)

main :: IO ()
main = readLn >>= flip replicateM_ (readLn >>= print . sumEvenFibos)

sumEvenFibos :: Int -> Int
sumEvenFibos n = sum . filter even $ takeWhile (<n) fibos

fibos :: [Int]
fibos = 1 : 2 : zipWith (+) fibos (tail fibos)
